site_name: Caesb

repo_name: '2023.1-Caesb'
repo_url: https://github.com/Requisitos-de-Software/2023.1-Caesb
site_url: https://requisitos-de-software.github.io/2023.1-Caesb/
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2023 Caesb

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js

theme:
  custom_dir: overrides
  name: material
  language: pt-BR
  logo: assets/imagens/logo.png
  favicon: assets/imagens/logo.png

  icon:
    repo: fontawesome/brands/github

  features:
    - toc.integrate 
    - toc.follow
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - navigation.instant
    - navigation.top    

  hide: 
    - 
    
  extra:
    social:
      - icon: fontawesome/brands/mastodon
        link: https://fosstodon.org/@squidfunk
    
  plugins: 
    - search:
        lang: pt-BR

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: dark blue
      accent: amber
      toggle:
        icon: custom-icons/contrast-light
        name: Modo Claro
    
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: yellow
      toggle:
        icon: custom-icons/contrast-dark
        name: Modo Escuro

nav:
  - Home: index.md
  - Planejamento: 
    - Aplicativo Escolhido: Planejamento/aplicativo_escolhido.md
    - Metodologia: Planejamento/metodologias.md
    - Ferramentas: Planejamento/ferramentas.md
    - Cronograma: Planejamento/cronograma.md
    - Cronograma Realizado: Planejamento/cronograma_realizado.md
    - Heatmap: Planejamento/heatmap.md
  - Rastreabilidade:
    - Pré-Rastreabilidade: Pre-rastreabilidade/aplicativos_analisados.md
    - Pós-Rastreabilidade:
      - Forward-Form: Pos-Rastreabilidade/ForwardFrom.md
  - Elicitação:
    - Perfil do Usuário: Elicitacao/perfil_usuario.md
    - Personas: Elicitacao/personas.md
    - Questionário: Elicitacao/questionario.md
    - Introspecção: Elicitacao/introspeccao.md
    - Storytelling: Elicitacao/storytelling.md
    - Priorizaçao: 
      - Metodologias: Elicitacao/priorizacao.md
      - First Things First: Elicitacao/priorizacao-FTF.md
      - In or Out: Elicitacao/priorizacaoInOrOut.md
  - Modelagem:
    - Cenários: Modelagem/cenarios.md
    - Léxicos: Modelagem/lexicos.md
    - Casos de Uso: Modelagem/casos_de_uso.md
    - Especificação Suplementar: Modelagem/especificacao_suplementar.md
    - Ágil: 
      - Backlog: Modelagem/Agil/backlog.md
      - Histórias de Usuário: Modelagem/Agil/historia_usuario.md
      - NFR Framework: Modelagem/Agil/NFR.md
  - Verificação:
      - Caesb:
        - Planejamento Geral: Verificacao/Caesb/0planejamento-geral.md
        - Entrega 1:
          - Planejamento: Verificacao/Caesb/Entrega1/0planejamento.md
          - Cronograma Planejado: Verificacao/Caesb/Entrega1/Cronograma_Planejado.md
          - Cronograma Realizado: Verificacao/Caesb/Entrega1/Cronograma_Realizado.md
          - Atas: Verificacao/Caesb/Entrega1/Atas.md
          - Ferramentas: Verificacao/Caesb/Entrega1/Ferramentas.md
          - Metodologias: Verificacao/Caesb/Entrega1/Metodologias.md
          - Aplicativo Selecionado: Verificacao/Caesb/Entrega1/Aplicativo_Selecionado.md
          - Rich Picture: Verificacao/Caesb/Entrega1/Rich_Picture.md
        - Entrega 2: 
          - Planejamento: Verificacao/Caesb/Entrega2/0planejamento.md
          - Questionário: Verificacao/Caesb/Entrega2/elicitacao/questionario.md
          - Perfil de Usuário: Verificacao/Caesb/Entrega2/elicitacao/perfilUsuario.md
          - Personas: Verificacao/Caesb/Entrega2/elicitacao/personas.md
          - Introspecção: Verificacao/Caesb/Entrega2/elicitacao/introspeccao.md
          - Storytelling: Verificacao/Caesb/Entrega2/elicitacao/storytelling.md
          - InOrOut: Verificacao/Caesb/Entrega2/priorizacao/InOrOut.md
          - First Things First:  Verificacao/Caesb/Entrega2/priorizacao/FTF.md
        - Entrega 3: 
          - Planejamento: Verificacao/Caesb/Entrega3/0planejamento.md
          - Cenários: Verificacao/Caesb/Entrega3/cenarios.md
          - Casos de Uso: Verificacao/Caesb/Entrega3/casos-de-uso.md
          - Léxicos: Verificacao/Caesb/Entrega3/lexicos.md
          - Especificação Suplementar: Verificacao/Caesb/Entrega3/esp-suplementar.md
        - Entrega 4:
          - Planejamento: Verificacao/Caesb/Entrega4/0planejamento.md
          - Histórias de Usuário: Verificacao/Caesb/Entrega4/historias.md
          - Backlog: Verificacao/Caesb/Entrega4/backlog.md
          - NFR: Verificacao/Caesb/Entrega4/nfr.md
        - Validação: Validacao/validacao.md
      - Grupo 5:
        - Entrega 1:
          - Planejamento: Verificacao/Grupo5/Entrega1/Entrega1.md
          - Cronograma Planejado: Verificacao/Grupo5/Entrega1/Cronograma_Planjeado.md
          - Cronograma Realizado: Verificacao/Grupo5/Entrega1/Cronograma_Realizado.md
          - Atas: Verificacao/Grupo5/Entrega1/Atas.md
          - Ferramentas: Verificacao/Grupo5/Entrega1/Ferramentas.md
          - Metodologias: Verificacao/Grupo5/Entrega1/Metodologias.md
          - Aplicativo Selecionado: Verificacao/Grupo5/Entrega1/Aplicativo_Selecionado.md
          - Rich Picture: Verificacao/Grupo5/Entrega1/Rich_Picture.md
        - Entrega 2: 
          - Elicitação: 
            - Planejamento: Verificacao/Grupo5/Entrega2/elicitacao/planejamento-elicitacao.md
            - Perfil de Usuário: Verificacao/Grupo5/Entrega2/elicitacao/questionario.md
            - Personas: Verificacao/Grupo5/Entrega2/elicitacao/personas.md
            - Storytelling: Verificacao/Grupo5/Entrega2/elicitacao/storytelling.md
            - Glossário: Verificacao/Grupo5/Entrega2/elicitacao/glossario.md
            - Introspecção: Verificacao/Grupo5/Entrega2/elicitacao/introspeccao.md
            - Entrevista:  Verificacao/Grupo5/Entrega2/elicitacao/entrevista.md
            - Brainstorming: Verificacao/Grupo5/Entrega2/elicitacao/brainstorming.md
          - Priorização: 
            - Planejamento: Verificacao/Grupo5/Entrega2/priorizacao/planejamento-Priorizacao.md
            - First Things First:  Verificacao/Grupo5/Entrega2/priorizacao/FTF.md
            - MoScoW: Verificacao/Grupo5/Entrega2/priorizacao/moscow.md
            - Three Level Scale ou TLS: Verificacao/Grupo5/Entrega2/priorizacao/tls.md
        - Entrega 3: 
          - Cenários: Verificacao/Grupo5/Entrega3/cenarios.md
          - Casos de Uso: Verificacao/Grupo5/Entrega3/casos-de-uso.md
          - Léxicos: Verificacao/Grupo5/Entrega3/lexicos.md
          - Especificação Suplementar: Verificacao/Grupo5/Entrega3/esp-suplementar.md
        - Entrega 4:
          - Planejamento: Verificacao/Grupo5/Entrega4/planejamento.md
          - Histórias de Usuário: Verificacao/Grupo5/Entrega4/historias.md
          - Backlog: Verificacao/Grupo5/Entrega4/backlog.md
          - NFR: Verificacao/Grupo5/Entrega4/nfr.md
  - Pós-Rastreabilidade:
    - Backward-From: Pos-rastreabilidade/backward_from.md
    - Forward-From: Pos-Rastreabilidade/ForwardFrom.md
    - Matriz de Rastreabilidade: Pos-rastreabilidade/matriz.md
  - Atas:
    - Atas/Reuniao01.md
    - Atas/Reuniao02.md
    - Atas/Reuniao03.md
    - Atas/Reuniao04.md
  - Guia: 
    - Guia/Mkdocs.md
    - Guia/AdicionandoIcones.md
    - Fazendo a verificação:
      - Planejamento Geral: Guia/Verificacao/0planejamento-geral.md
      - Planejamento da Entrega: Guia/Verificacao/Entrega-Modelo/0planejamento.md
      - Artefato: Guia/Verificacao/Entrega-Modelo/1artefato.md
  - Entregas: Apresentacoes/apresentacoes.md
  - Entrega Final: EntregaFinal/entrega-final.md


markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

  # TESTE 1
  

  # Ordem das pastas
  # - Planejamento: 
  #     - Metodologia: 
  #     - Ferramentas: 
  #     - Cronograma: 
  #     - Aplicativos analisados: 
  # - Pré-Rastreabilidade:
  #     - Rich Picture: 
  # - Elicitação:
  #     - Perfil do usuário: 
  #     - Personas: 
  #     - Storytelling: 
  #     - Brainstorm: 
  #     - Observação: 
  #     - Priorização:
  # - Modelagem:
  #     - Cenários: 
  #     - Léxicos: 
  #     - Casos de Uso: 
  #     - Especifição Suplementar: 
  #     - Ágil:
  # - Análise de Requisitos:
  # - Pós-Rastreabilidade:
  # - Apresentações:
  #     - Etapa 1 - xx/xx/xxxx:
  #     - Etapa 2 - xx/xx/xxxx:
  #     - Etapa 3 - xx/xx/xxxx:
  #     - Etapa 4 - xx/xx/xxxx:
  #     - Etapa 5 - xx/xx/xxxx:
  #     - Etapa 6 - xx/xx/xxxx:
  #     - Etapa 7 - xx/xx/xxxx:
  #     - Entrega Final - xx/xx/xxxx:
  # - Entrega Final:
  #     - Entrega Final:
  # -Guia:
